# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modelPaciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('apellido_paterno', models.CharField(max_length=50, verbose_name='apellido_paterno')),
                ('apellido_materno', models.CharField(max_length=50, verbose_name='apellido_materno')),
                ('dni', models.CharField(max_length=50, verbose_name='dni')),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha de nacimiento')),
                ('direccion', models.CharField(max_length=50, verbose_name='direccion')),
                ('telefono_fijo', models.IntegerField(blank=True, null=True)),
                ('telefono_movil', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('fecha_alta', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
