# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-05 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_auto_20170605_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpaciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
